### ISSUE TITLE
Model Show in Black and white 

### ISSUE THREAD

**Issue by ehabme** [CariusLars/ar_flutter_plugin#103]
hello , everyone
i have a aproblem with plugin in Colors , i see model show as grey or black and white , i don't know why (screenshot attached)!

well done guys , really good plugin .

![image](https://user-images.githubusercontent.com/73368872/166611073-19a9d24b-a5d8-4ed5-bc14-a430983e2405.png)

**Comment by ehabme** [comment]
hello everyone , any updates ?
thanks

**Comment by Romna2208** [comment]
Hello !

I have the almost exact same problem :)

We have a waypoint we need to show in AR. 
Here it is :
[model.zip](https://github.com/CariusLars/ar_flutter_plugin/files/8737118/model.zip)

It works well on android, but on ios it's completly black no matter what i try. I tried exporting the object with lights, materials, textures, ... There is no grey like on this bed tho.
I'm not too sure what I can try next ?

Thanks a lot !

**Comment by giovannicampagnolo** [comment]
I have the same problem

**Comment by giovannicampagnolo** [comment]
i solve my problem with a fork of plugin and after that i modify the file iosArView

at line 233 you can solve the problem

<img width="885" alt="Schermata 2022-10-27 alle 10 58 20" src="https://user-images.githubusercontent.com/115693598/198240481-3c99fe5f-71de-4a0c-aa6b-90fe366b26bf.png">

**Comment by CariusLars** [comment]
I´ve added this to release 0.7.2 👍 thanks for solving this, feel free to PR with your forked version next time so everyone gets your fixes ASAP :) Keep up the good work!
