### ISSUE TITLE
Implement ARCORE Argumented Face with this package

### ISSUE THREAD

**Issue by PeterTF656** [CariusLars/ar_flutter_plugin#11]
Hi Lars, guten tag! Thank you for making this package happen! I have a question: Is it possible to use the [argumented face](https://developers.google.com/ar/develop/java/augmented-faces) with this package at this stage?

**Comment by CariusLars** [comment]
Hi Peter! Unfortunately, the feature is not available in the plugin yet. If you're working with augmented faces and want to use Flutter, it would be awesome if you would fork the repo and add the feature in a pull request, I'm happy to any questions on where to get started!

**Comment by busterbogheart** [comment]
Yea do it yourself!
