### ISSUE TITLE
How can i rotate and move my web .glb object 

### ISSUE THREAD

**Issue by giovannicampagnolo** [CariusLars/ar_flutter_plugin#152]
I can't move or rotate my .glb object from web is possible to do?

@CariusLars

**Comment by JeroenMoonen** [comment]
You should have a look at the examples:

https://github.com/CariusLars/ar_flutter_plugin/blob/main/example/lib/examples/objectgesturesexample.dart

**Comment by giovannicampagnolo** [comment]
yes i've already follow this example but it didn't work
@JeroenMoonen

**Comment by JeroenMoonen** [comment]
What does your log say?

**Comment by giovannicampagnolo** [comment]
nothing

**Comment by JeroenMoonen** [comment]
Does it work when you clone the repository and start the example?

**Comment by giovannicampagnolo** [comment]
didn't work

**Comment by giovannicampagnolo** [comment]
after 7 days of testing i found the problem 

The gesture used for rotation and panning are really unfrendly
Then i think is the case to resolve this
