### ISSUE TITLE
UI buttons in ARView

### ISSUE THREAD

**Issue by zManu4K** [CariusLars/ar_flutter_plugin#199]
Hello, im facing this issue, i cant place buttons/ui directly on the screen of ARView. Id like to have a fullscreen of ARView and then a couple buttons for user interface, i tried many ways but with no results, its seems like the button is visible for a fraction of second then it disappear, similar to a wrong setup of the stack widget. 

`@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(children: [
          ARView(
            onARViewCreated: onARViewCreated,
            planeDetectionConfig: PlaneDetectionConfig.horizontalAndVertical,
          ),
           Align(
                      child:
                            IconButton(onPressed: doSomething, icon: Icon(Icons.abc))
                    ),
        ]));
  }`

Am I using it not properly? Thanks a lot in advance

**Comment by AlbaneseRemy** [comment]
Did you try adding an alignment and a size to your Icon?
I got it working with that:

`  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          ARView(
            onARViewCreated: onARViewCreated,
            planeDetectionConfig: PlaneDetectionConfig.horizontalAndVertical,
          ),
          Align(alignment: FractionalOffset.bottomCenter, child: IconButton(onPressed: doSomething, icon: const Icon(Icons.abc, size: 50))),
        ],
      ),
    );
  }`

**Comment by zManu4K** [comment]
Im retarded
