### ISSUE TITLE
Missing `customPlaneTexturePath` asset

### ISSUE THREAD

**Issue by leeprobert** [CariusLars/ar_flutter_plugin#21]
Couldn't find the `Images/triangle.png` asset.

**Comment by CariusLars** [comment]
Hey @leeprobert , could you provide some more info please? Did you import the plugin into your own Flutter app or did you try to compile the example app? What is the exact error the compiler throws?

**Comment by leeprobert** [comment]
Sorry, my bad. I was looking for your assets folder, and didn't see it in the `Examples` folder.
