### ISSUE TITLE
Include Snapshot functionality for both iOS and Android

### ISSUE THREAD

**Issue by leeprobert** [CariusLars/ar_flutter_plugin#22]
I added a `snapshot` method to the `ARKit` package for iOS and noticed the `ARCore` package also has a `snapshot` method that was implemented via a pull request. Would be great to have this functionality included here too. Ideally, it should return a `Future<ImageProvider>` so the user can deal with the image themselves once it has been created.

**Comment by leeprobert** [comment]
@CariusLars - would you be up for some paid work to get this feature sorted for iOS and Android? There's also the local filesystem load of GLB files that I have started but am getting an error. I am working on a live project that requires these features so I have to get it done quite soon. Am happy to pay.

**Comment by CariusLars** [comment]
@leeprobert can you send me an email to lars@carius.io and let me know at what times you'd be available? Let's set up a quick call to talk about possibly turning this into a paid project!

**Comment by CariusLars** [comment]
added in v0.5.0
