### ISSUE TITLE
Augmented Faces for ARCore functions

### ISSUE THREAD

**Issue by KotadiyaHiral** [CariusLars/ar_flutter_plugin#23]
Is Augmented Faces - ARCore - IOS functionality supported by this plugin? 

https://developers.google.com/ar/develop/ios/augmented-faces/developer-guide

If not then please add Augmented Faces functionality to the plugin

**Comment by CariusLars** [comment]
Issue #18 covers the same topic, so let's move the discussion there. In short: no, it's not supported yet, but I agree that it should be one of the next steps on the roadmap. Maybe you'd like to contribute by adding the functionality? I'm always happy to help and assist
