### ISSUE TITLE
Model from local file system

### ISSUE THREAD

**Issue by i-panov** [CariusLars/ar_flutter_plugin#27]
Hello! Please tell me how to load the model saved to the device? `ArNode.uri` supports only assets and links.

**Comment by CariusLars** [comment]
Hi @i-panov, did you have a look at the [Code example for loading models from the local file system and from online resources](https://github.com/CariusLars/ar_flutter_plugin/blob/main/example/lib/examples/localandwebobjectsexample.dart)? As you can see in there, you have to place you model inside the flutter asset folder of your app (NOT the asset folder of the AR Flutter plugin), then you can simply provide the path to the `ARNode`'s `uri` property and load the locally saved model.
Best
Lars

**Comment by i-panov** [comment]
@CariusLars Yes, I looked at this particular example. This is the load from assets, and I need it from the phone's file system.

**Comment by CariusLars** [comment]
Hi @i-panov , sorry for the misunderstanding, now I get it! You're right, the plugin actually doesn't support loading from models from the device's file system, but that can be added easily. I suggest you fork the repo and add the function, it would be great if you could create a pull request afterwards so I can include it in the next release!
Here are some pointers on how to do it:
- I suggest you add a new [nodeType](https://github.com/CariusLars/ar_flutter_plugin/blob/main/lib/datatypes/node_types.dart), e.g. `fileSystemGltf` 
- In the [AndroidARView](https://github.com/CariusLars/ar_flutter_plugin/blob/main/android/src/main/kotlin/io/carius/lars/ar_flutter_plugin/AndroidARView.kt) on line 473, add a case for the new node type that doesn'T use the Flutter loader but rather uses the file path provided in the `ARNode`'s `uri` property right away to pass to the [ARModelBuilder](https://github.com/CariusLars/ar_flutter_plugin/blob/main/android/src/main/kotlin/io/carius/lars/ar_flutter_plugin/ArModelBuilder.kt)'s function `makeNodeFromGltf`
- To the same for the [IosARView](https://github.com/CariusLars/ar_flutter_plugin/blob/main/ios/Classes/IosARView.swift) (line 280)

Let me know if you struggle at any point :) 

Cheers
Lars

**Comment by i-panov** [comment]
It worked, thanks!

**Comment by CariusLars** [comment]
Nice! Would be really cool if you could open a pull request with the code you added so others in the community can profit from your contribution :)

**Comment by leeprobert** [comment]
I am facing the same issue. Have you rolled this into the last release?

**Comment by leeprobert** [comment]
I am trying to implement this myself but `makeNodeFromGltf` is failing when I pass the path uri. I'm only working on an iOS implementation too so would it be worth joining forces to get this in? I need to do the `snapshot` feature too, so would like to get this done ASAP.

**Comment by leeprobert** [comment]
When I pass the URI to the `GLTFSceneSource` class it fails. The path string I am sending as the `name` attribute is: `/var/mobile/Containers/Data/Application/DC0F7267-7901-470D-A834-84B0E5B40FF1/Documents/statue.glb` so I'm not sure this line: `Bundle.main.path(forResource: name, ofType: nil)` is handling that resource name properly.

@i-panov - how did you do this when you fixed the issue?

![GLTFSceneSource_error](https://user-images.githubusercontent.com/151336/132878571-1be0a794-1752-4291-81e2-b98a10497605.jpg)

**Comment by naveenbharadwaj19** [comment]
@CariusLars Itried to load the file from` /data/user/0/com.cart.app/app_flutter/file_picker/Duck.glb` still same issue

**Comment by naveenbharadwaj19** [comment]
@CariusLars I've seen the [example](https://github.com/CariusLars/ar_flutter_plugin/blob/main/example/lib/examples/localandwebobjectsexample.dart). got the file from file picker and created a file in path from `getApplicationDocumentsDirectory` . But still i'm getting `unable to load the model` why ? 

Snippet:
```dart
Directory appDocDir = await getApplicationDocumentsDirectory();
String fileName = result.files.single.name; // duck.glb
File file = File("${appDocDir.path}/$fileName");
await file.create();
```
**current path** : `/data/data/com.demo.app/app_flutter/Duck.glb`

![path_photo](https://user-images.githubusercontent.com/63662884/146759598-e2670551-fef8-4601-8c57-afbaa9c870b5.jpg)

**Comment by naveenbharadwaj19** [comment]
Figured out . The problem is  i was adding the whole path . Now it's working 

```dart
ARNode(
    type: NodeType.fileSystemAppFolderGLB,
    uri:  fileName, // duck.glb
    scale: Vector3(0.5, 0.5, 0.5),
    position: Vector3(0.0, 0.0, 0.0),
    rotation: Vector4(1.0, 0.0, 0.0, 0.0),
      );
```

**Comment by PrabhatAkhoon** [comment]
Is the issue about local file system resolved? Because i am getting errors about "unable to renderable file.glb".

**Comment by DreaserousProductions** [comment]
This wont work for me...

I keep getting "Unable to load renderable"

**Comment by janWICKEDpro** [comment]
#

> This wont work for me...
> 
> I keep getting "Unable to load renderable"

Me too. Any solutions to this ?

**Comment by Sudharsan009** [comment]
is there any anyone resolve this issue?
I also keep getting "Unable to load renderable"
