### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ar_flutter_plugin"

### ISSUE THREAD

**Issue by leahracquel** [CariusLars/ar_flutter_plugin#28]
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ar_flutter_plugin"
  In Podfile:
    ar_flutter_plugin (from `.symlinks/plugins/ar_flutter_plugin/ios`)

Specs satisfying the `ar_flutter_plugin (from `.symlinks/plugins/ar_flutter_plugin/ios`)` depency were found, but they required a higher minimum deployment target.

----
Already set deployment target from 9 to 14
Still error persists

**Comment by CariusLars** [comment]
Hey @leahracquel, could you provide some more information on where the error occurs please? Are you trying to compile your own app that uses the plugin or the example app of the plugin itself? 
I just ran `pod install`in both the ios folder of the example app and in the ios folder of another Flutter app of mine that uses the plugin and that targets iOS 13.0, both ran without errors

**Comment by leahracquel** [comment]
I cannot compile my own app and the example app since on `pod install` it already occurs.
Tried to rebuild and clean the project and app but error persists.

May i know the minimum target IOS?

**Comment by CariusLars** [comment]
Are you running everything from the command line or in XCode itself? If in XCode,make sure to open the xcworkspace, not the xcproject file. Also, in a fresh clone of the repo, it might be worth running `flutter pub get` and `flutter build ios` to make sure the flutter environment is set up correctly before running `pod install`. If you do that, please paste your output here.

Another idea would be deleting the podfile.lock as this can cause problems if it's outdated.

the minimum target iOS should be 13.0, but in the sample app of the plugin, all of this is already specified and I can build it without problems, so you shouldn't have to change anything there.

**Comment by digitalrbnz** [comment]
The minDeployment version needs to be over 30.

**Comment by Ramonfan** [comment]
utomatically signing iOS for device deployment using specified development team in Xcode project: 5TD7B79GK6
Running pod install...                                           2,408ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.7.0`
      > Copying FirebaseFirestore from
      `/Users/csmac05/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/c3b6c92018f885870de3f97721641333` to
      `Pods/FirebaseFirestore`
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `ar_flutter_plugin` from `.symlinks/plugins/ar_flutter_plugin/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    cloud_firestore: Using user specified Firebase SDK version '8.7.0'
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using user specified Firebase SDK version '8.7.0'
    -> Fetching podspec for `flutter_archive` from `.symlinks/plugins/flutter_archive/ios`
    -> Fetching podspec for `geolocator_apple` from `.symlinks/plugins/geolocator_apple/ios`
    -> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/ios`
    -> Fetching podspec for `permission_handler_apple` from `.symlinks/plugins/permission_handler_apple/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_d_b.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/d/d/b/GLTFSceneKit/0.3.0/GLTFSceneKit.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_d_d.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/c/d/d/SwiftJWT/3.6.200/SwiftJWT.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_e_a.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/4/e/a/ARCore/1.35.0/ARCore.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/4/e/a/ARCore/1.33.0/ARCore.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.4.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_6_1.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/1/6/1/ZIPFoundation/0.9.16/ZIPFoundation.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_8_b_d.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/10.4.0/FirebaseCore.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/4/e/a/ARCore/1.33.0/ARCore.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_e_3.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/3.1.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.1/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.2/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.4.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.5.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.6.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.6.1/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.7.0/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.7.1/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.7.2/GTMSessionFetcher.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_e.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/4/e/a/ARCore/1.33.0/ARCore.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.1.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.1.1/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.2.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.3.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.6.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.6.1/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.8.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.9.0/Firebase.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?


    ### Stack

    ```
       CocoaPods : 1.11.3
            Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
        RubyGems : 3.3.11
            Host : macOS 12.5.1 (21G83)
           Xcode : 14.0.1 (14A400)
             Git : git version 2.37.0 (Apple Git-136)
    Ruby lib dir : /opt/homebrew/Cellar/ruby/3.1.2_1/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '13.0'

    # Override firebase SDK version for compatibility reasons
    $FirebaseSDKVersion = '8.7.0'
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get
        is executed first"
      end

      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter
      pub get"
    end

    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

    flutter_ios_podfile_setup

    target 'Runner' do
      use_frameworks!
      use_modular_headers!

      pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.7.0' # This line
      improves build times (see https://firebase.flutter.dev/docs/overview/)
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.camera
            'PERMISSION_CAMERA=1',

            ## dart: PermissionGroup.photos
            'PERMISSION_PHOTOS=1',

            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
            'PERMISSION_LOCATION=1',

            ## dart: PermissionGroup.sensors
            'PERMISSION_SENSORS=1',

            ## dart: PermissionGroup.bluetooth
            'PERMISSION_BLUETOOTH=1',

          ]
        end
      end
    end
    ```

    ### Error

    ```
    JSON::ParserError - 451: unexpected token at '"~> 8.9.0-be'
    /opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/json/common.rb:216:in `parse'
    /opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/json/common.rb:216:in `parse'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in
    `from_json'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in
    `from_string'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver/lazy_specification.rb:37:in
    `specification'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver/lazy_specification.rb:29:in
    `subspec_by_name'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:362:in `block in
    specifications_for_dependency'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:362:in `map'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:362:in
    `specifications_for_dependency'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in
    sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in
    `block in sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in
    `with_no_such_dependency_error_handling'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in
    `sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in
    `push_state_for_requirements'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in
    `require_nested_dependencies_for'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in
    resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in
    `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in
    resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

**Comment by ghost** [comment]
adding `platform :ios, '13.0'` to the Podfile resolved for me
