### ISSUE TITLE
Loading models

### ISSUE THREAD

**Issue by roby0970** [CariusLars/ar_flutter_plugin#30]
This package helped me a lot, so first, thanks for that!

The problem? I cannot load any model except for the ones from example. Chicken from local and a duck from web. I have 0 knowledge of 3d models and how they work, but I tried to load:

- localGLTF2 -> all 4 versions from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box

after adding, nodes are registered as added but nothing shows in space, nor are there any error messages. 

Using the code from example and only using my models. Also, created a folder and put the .gltf in there while adding the folder path to assets, just as it is with Chicken model.

**Comment by roby0970** [comment]
Yup, the buggy works... I need something netrual, simple, so I'm just gonna try loading models until I find a working one.

Im gonna close this issue for now then. Thanks!

**Comment by CariusLars** [comment]
@roby0970 there are loads of free models out there on the internet, but you can also just use blender (it's free) to create your own box or any other simple model and save it as gltf :)
