### ISSUE TITLE
I can't dispose camera in ar_flluter_plugin

### ISSUE THREAD

**Issue by Koobonik** [CariusLars/ar_flutter_plugin#59]
I'm using ar_flutter_plugin: ^0.6.0
In the app I make, I turn off and turn on AR several times.
However, even if I pop after using AR, the camera connection will not be disconnected.
In fact, the green dot does not disappear in the upper right corner.
If you do this action about 12 times on my iPhone 12 pro max, the app will be shut down with this error
at the same, my Galaxy s21 do this action about 25~30 times.

----

* thread #67, queue = 'com.apple.arkit.technique.prepare', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=3072 MB, unused=0x0)
    frame #0: 0x00000001c30736dc AppleCV3D`___lldb_unnamed_symbol5156$$AppleCV3D + 1848
AppleCV3D`___lldb_unnamed_symbol5156$$AppleCV3D:
->  0x1c30736dc <+1848>: str    w9, [x8]
    0x1c30736e0 <+1852>: str    d0, [x8, #0x8]
    0x1c30736e4 <+1856>: ldr    x8, [x23]
    0x1c30736e8 <+1860>: add    x9, x8, #0x1              ; =0x1 
Target 0: (Runner) stopped.

----

I have confirmed that the camera is disposed through the internal library, but it is estimated that the mobile phone's resources are used continuously without actually disconnecting.

Perhaps the same phenomenon is expected in the sample app. Is there anything I'm missing?

Errors are occurring in the same way as Android and iOS.

my flutter doctor -v

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale
    ko-KR)
    • Flutter version 2.5.3 at /Users/dev_koo/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dev_koo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

https://user-images.githubusercontent.com/15663052/143444304-f5b1a42d-f7b3-4dd3-90ce-1cfed1498abb.mp4

**Comment by Koobonik** [comment]
I resolved this problem.

Can I pull reqeust to other branch?

**Comment by CariusLars** [comment]
awesome @Koobonik !
Yeah definitely, create a PR to the `develop` branch and I will run a few tests and create a new release version of the plugin with your fixes :)

**Comment by Koobonik** [comment]
Hello @CariusLars !
I did pull request 2 days ago
Can I know the next update schedule?

**Comment by CariusLars** [comment]
Hey @Koobonik ,
I just reviewed your PR and published v0.6.1 on the `main` branch including your commits :)
Thank's for your contribution, really appreciate it!
