### ISSUE TITLE
Is it possible to enable ARCore Depth API ? 

### ISSUE THREAD

**Issue by raysonlim77** [CariusLars/ar_flutter_plugin#65]
Is it possible to enable ARCore Depth API in this plugin?  I have enable the ARCore Cloud Anchor API for my app and it work fine. but it would be fantastic if we can use the ARCore Depth API feature. by the way , i hope you can add the delete selected node function in your example just like the onRemoveEverything function.

**Comment by CariusLars** [comment]
hey @raysonlim77 ,
unfortunately the version of Sceneform used in this plugin does not support the Depth API feature. I suggest migrating to the community-supported Sceneform at some point (see [https://github.com/CariusLars/ar_flutter_plugin/issues/16](https://github.com/CariusLars/ar_flutter_plugin/issues/16) ) as this would enable us to use Depth API. Is this something you might want to look into?

**Comment by raysonlim77** [comment]
Yes,That's exactly what im looking for, but i have no idea how to migrate it, Im looking forward to see this feature available in this plugin. anyway i truly appreciate your kind suggestion.
