### ISSUE TITLE
Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

### ISSUE THREAD

**Issue by thomtomdup** [CariusLars/ar_flutter_plugin#73]
Hello.
I have this issue when i want to run the exemple available in this git directory. But i have this issue when i want to test in IOS 15.2 on iphone 13 :
    
`2021-12-30 13:35:16.420 xcodebuild[53516:26525348] [MT] PluginLoading: Required plug-in compatibility UUID 7A3A18B7-4C08-46F0-A96A-AB686D315DF0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs`

I tried to update the packages in this package's directory pubspec.yaml file and also in the exemple's directory pubspec.yaml file but the issue steel.
Do you have some solution to solve this issue ? Alcatraz is an unavailable and obsolete/deprecated plugin .

Thank you very much in advance.
Regards.

**Comment by CariusLars** [comment]
this sounds like an xcode issue to me, are you running an up-to-date version?

**Comment by thomtomdup** [comment]
Hello.
Yes it's the last version and all of other mobile projects work fine.
The version is Version 13.2.1 (13C100).

**Comment by CariusLars** [comment]
okay, weird... Alcatraz shouldn't even be a part of this plugin, it's not used anywhere, so this feels more like a problem with xcode to me. Not sure how to help with this. Have you tried running `flutter build ios` from the console (within the `example` folder)?

**Comment by thomtomdup** [comment]
Hello.
I had run with xcode and after with flutter ( Android Studio ) and all run now. I don't know what was the issue, may be compilation cache issue. But now all work good. Sorry for the disturb.
